---
driver:
  name: podman
  options:
    managed: false
    login_command_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
platforms:
  - name: ubuntu-24.04
    image: docker.io/ursamajorlab/noble-python:3.12
provisioner:
  name: ansible
verifier:
  name: ansible
