name: artemisbeta.ubuntu_setup.pyenv
on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: 🥡 Checkout Repository
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: 📥 Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
      - name: 🧪 Run Tests with Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: ${{ github.repository }}/roles/pyenv
          molecule_args: --scenario-name ci
